export const keysRowE = [
  {
    name: 'Backquote',
    lowerCaseValue: { Eng: '`', Rus: 'ё' },
    upperCaseValue: { Eng: '~', Rus: 'Ё' },
    type: 'alphanumeric',
  },
  {
    name: 'Digit1',
    lowerCaseValue: { Eng: '1', Rus: '1' },
    upperCaseValue: { Eng: '!', Rus: '!' },
    type: 'alphanumeric',
  },
  {
    name: 'Digit2',
    lowerCaseValue: { Eng: '2', Rus: '2' },
    upperCaseValue: { Eng: '@', Rus: '"' },
    type: 'alphanumeric',
  },
  {
    name: 'Digit3',
    lowerCaseValue: { Eng: '3', Rus: '3' },
    upperCaseValue: { Eng: '#', Rus: '№' },
    type: 'alphanumeric',
  },
  {
    name: 'Digit4',
    lowerCaseValue: { Eng: '4', Rus: '4' },
    upperCaseValue: { Eng: '$', Rus: ';' },
    type: 'alphanumeric',
  },
  {
    name: 'Digit5',
    lowerCaseValue: { Eng: '5', Rus: '5' },
    upperCaseValue: { Eng: '%', Rus: '%' },
    type: 'alphanumeric',
  },
  {
    name: 'Digit6',
    lowerCaseValue: { Eng: '6', Rus: '6' },
    upperCaseValue: { Eng: '^', Rus: ':' },
    type: 'alphanumeric',
  },
  {
    name: 'Digit7',
    lowerCaseValue: { Eng: '7', Rus: '7' },
    upperCaseValue: { Eng: '&', Rus: '?' },
    type: 'alphanumeric',
  },
  {
    name: 'Digit8',
    lowerCaseValue: { Eng: '8', Rus: '8' },
    upperCaseValue: { Eng: '*', Rus: '*' },
    type: 'alphanumeric',
  },
  {
    name: 'Digit9',
    lowerCaseValue: { Eng: '9', Rus: '9' },
    upperCaseValue: { Eng: '(', Rus: '(' },
    type: 'alphanumeric',
  },
  {
    name: 'Digit0',
    lowerCaseValue: { Eng: '0', Rus: '0' },
    upperCaseValue: { Eng: ')', Rus: ')' },
    type: 'alphanumeric',
  },
  {
    name: 'Minus',
    lowerCaseValue: { Eng: '-', Rus: '-' },
    upperCaseValue: { Eng: '_', Rus: '_' },
    type: 'alphanumeric',
  },
  {
    name: 'Equal',
    lowerCaseValue: { Eng: '=', Rus: '=' },
    upperCaseValue: { Eng: '+', Rus: '+' },
    type: 'alphanumeric',
  },
  {
    name: 'Backspace',
    lowerCaseValue: { Eng: '', Rus: '' },
    upperCaseValue: { Eng: '', Rus: '' },
    type: 'functional',
  },
];
export const keysRowD = [
  {
    name: 'Tab',
    lowerCaseValue: { Eng: '\t', Rus: '\t' },
    upperCaseValue: { Eng: '\t', Rus: '\t' },
    type: 'functional',
  },
  {
    name: 'KeyQ',
    lowerCaseValue: { Eng: 'q', Rus: 'й' },
    upperCaseValue: { Eng: 'Q', Rus: 'Й' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyW',
    lowerCaseValue: { Eng: 'w', Rus: 'ц' },
    upperCaseValue: { Eng: 'W', Rus: 'Ц' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyE',
    lowerCaseValue: { Eng: 'e', Rus: 'у' },
    upperCaseValue: { Eng: 'E', Rus: 'У' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyR',
    lowerCaseValue: { Eng: 'r', Rus: 'к' },
    upperCaseValue: { Eng: 'R', Rus: 'К' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyT',
    lowerCaseValue: { Eng: 't', Rus: 'е' },
    upperCaseValue: { Eng: 'T', Rus: 'Е' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyY',
    lowerCaseValue: { Eng: 'y', Rus: 'н' },
    upperCaseValue: { Eng: 'Y', Rus: 'Н' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyU',
    lowerCaseValue: { Eng: 'u', Rus: 'г' },
    upperCaseValue: { Eng: 'U', Rus: 'Г' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyI',
    lowerCaseValue: { Eng: 'i', Rus: 'ш' },
    upperCaseValue: { Eng: 'I', Rus: 'Ш' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyO',
    lowerCaseValue: { Eng: 'o', Rus: 'щ' },
    upperCaseValue: { Eng: 'O', Rus: 'Щ' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyP',
    lowerCaseValue: { Eng: 'p', Rus: 'з' },
    upperCaseValue: { Eng: 'P', Rus: 'З' },
    type: 'alphanumeric',
  },
  {
    name: 'BracketLeft',
    lowerCaseValue: { Eng: '[', Rus: 'х' },
    upperCaseValue: { Eng: '{', Rus: 'Х' },
    type: 'alphanumeric',
  },
  {
    name: 'BracketRight',
    lowerCaseValue: { Eng: ']', Rus: 'ъ' },
    upperCaseValue: { Eng: '}', Rus: 'Ъ' },
    type: 'alphanumeric',
  },
  {
    name: 'Backslash',
    lowerCaseValue: { Eng: '\\', Rus: '\\' },
    upperCaseValue: { Eng: '|', Rus: '/' },
    type: 'alphanumeric',
  },
];
export const keysRowC = [
  {
    name: 'CapsLock',
    lowerCaseValue: { Eng: '', Rus: '' },
    upperCaseValue: { Eng: '', Rus: '' },
    type: 'functional',
  },
  {
    name: 'KeyA',
    lowerCaseValue: { Eng: 'a', Rus: 'ф' },
    upperCaseValue: { Eng: 'A', Rus: 'Ф' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyS',
    lowerCaseValue: { Eng: 's', Rus: 'ы' },
    upperCaseValue: { Eng: 'S', Rus: 'Ы' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyD',
    lowerCaseValue: { Eng: 'd', Rus: 'в' },
    upperCaseValue: { Eng: 'D', Rus: 'В' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyF',
    lowerCaseValue: { Eng: 'f', Rus: 'а' },
    upperCaseValue: { Eng: 'F', Rus: 'А' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyG',
    lowerCaseValue: { Eng: 'g', Rus: 'п' },
    upperCaseValue: { Eng: 'G', Rus: 'П' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyH',
    lowerCaseValue: { Eng: 'h', Rus: 'р' },
    upperCaseValue: { Eng: 'H', Rus: 'Р' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyJ',
    lowerCaseValue: { Eng: 'j', Rus: 'о' },
    upperCaseValue: { Eng: 'J', Rus: 'О' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyK',
    lowerCaseValue: { Eng: 'k', Rus: 'л' },
    upperCaseValue: { Eng: 'K', Rus: 'Л' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyL',
    lowerCaseValue: { Eng: 'l', Rus: 'д' },
    upperCaseValue: { Eng: 'L', Rus: 'Д' },
    type: 'alphanumeric',
  },
  {
    name: 'Semicolon',
    lowerCaseValue: { Eng: ';', Rus: 'ж' },
    upperCaseValue: { Eng: ':', Rus: 'Ж' },
    type: 'alphanumeric',
  },
  {
    name: 'Quote',
    lowerCaseValue: { Eng: "'", Rus: 'э' },
    upperCaseValue: { Eng: '"', Rus: 'Э' },
    type: 'alphanumeric',
  },
  {
    name: 'Enter',
    lowerCaseValue: { Eng: '\n', Rus: '\n' },
    upperCaseValue: { Eng: '\n', Rus: '\n' },
    type: 'functional',
  },
];
export const keysRowB = [
  {
    name: 'ShiftLeft',
    lowerCaseValue: { Eng: '', Rus: '' },
    upperCaseValue: { Eng: '', Rus: '' },
    type: 'functional',
  },
  {
    name: 'KeyZ',
    lowerCaseValue: { Eng: 'z', Rus: 'я' },
    upperCaseValue: { Eng: 'Z', Rus: 'Я' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyX',
    lowerCaseValue: { Eng: 'x', Rus: 'ч' },
    upperCaseValue: { Eng: 'X', Rus: 'Ч' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyC',
    lowerCaseValue: { Eng: 'c', Rus: 'с' },
    upperCaseValue: { Eng: 'C', Rus: 'С' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyV',
    lowerCaseValue: { Eng: 'v', Rus: 'м' },
    upperCaseValue: { Eng: 'V', Rus: 'М' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyB',
    lowerCaseValue: { Eng: 'b', Rus: 'и' },
    upperCaseValue: { Eng: 'B', Rus: 'И' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyN',
    lowerCaseValue: { Eng: 'n', Rus: 'т' },
    upperCaseValue: { Eng: 'N', Rus: 'Т' },
    type: 'alphanumeric',
  },
  {
    name: 'KeyM',
    lowerCaseValue: { Eng: 'm', Rus: 'ь' },
    upperCaseValue: { Eng: 'M', Rus: 'Ь' },
    type: 'alphanumeric',
  },
  {
    name: 'Comma',
    lowerCaseValue: { Eng: ',', Rus: 'б' },
    upperCaseValue: { Eng: '<', Rus: 'Б' },
    type: 'alphanumeric',
  },
  {
    name: 'Period',
    lowerCaseValue: { Eng: '.', Rus: 'ю' },
    upperCaseValue: { Eng: '>', Rus: 'Ю' },
    type: 'alphanumeric',
  },
  {
    name: 'Slash',
    lowerCaseValue: { Eng: '/', Rus: '.' },
    upperCaseValue: { Eng: '?', Rus: ',' },
    type: 'alphanumeric',
  },
  {
    name: 'ArrowUp',
    lowerCaseValue: { Eng: '⯅', Rus: '⯅' },
    upperCaseValue: { Eng: '⯅', Rus: '⯅' },
    type: 'alphanumeric',
  },
  {
    name: 'ShiftRight',
    lowerCaseValue: { Eng: '', Rus: '' },
    upperCaseValue: { Eng: '', Rus: '' },
    type: 'functional',
  },
];
export const keysRowA = [
  {
    name: 'ControlLeft',
    lowerCaseValue: { Eng: 'Ctrl', Rus: 'Ctrl' },
    upperCaseValue: { Eng: 'Ctrl', Rus: 'Ctrl' },
    type: 'functional',
  },
  {
    name: 'AltLeft',
    lowerCaseValue: { Eng: 'Alt', Rus: 'Alt' },
    upperCaseValue: { Eng: 'Alt', Rus: 'Alt' },
    type: 'functional',
  },
  {
    name: 'Space',
    lowerCaseValue: { Eng: ' ', Rus: ' ' },
    upperCaseValue: { Eng: ' ', Rus: ' ' },
    type: 'alphanumeric',
  },
  {
    name: 'AltRight',
    lowerCaseValue: { Eng: 'Alt', Rus: 'Alt' },
    upperCaseValue: { Eng: 'Alt', Rus: 'Alt' },
    type: 'functional',
  },
  {
    name: 'ArrowLeft',
    lowerCaseValue: { Eng: '⯇', Rus: '⯇' },
    upperCaseValue: { Eng: '⯇', Rus: '⯇' },
    type: 'alphanumeric',
  },
  {
    name: 'ArrowDown',
    lowerCaseValue: { Eng: '⯆', Rus: '⯆' },
    upperCaseValue: { Eng: '⯆', Rus: '⯆' },
    type: 'alphanumeric',
  },
  {
    name: 'ArrowRight',
    lowerCaseValue: { Eng: '⯈', Rus: '⯈' },
    upperCaseValue: { Eng: '⯈', Rus: '⯈' },
    type: 'alphanumeric',
  },
  {
    name: 'ControlRight',
    lowerCaseValue: { Eng: 'Ctrl', Rus: 'Ctrl' },
    upperCaseValue: { Eng: 'Ctrl', Rus: 'Ctrl' },
    type: 'functional',
  },
];
